# Generated by Django 5.1.7 on 2025-04-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('ficha_no', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('fechamod', models.DateTimeField(blank=True, null=True)),
                ('datosfijos', models.CharField(blank=True, max_length=60, null=True)),
                ('etiquetasmar', models.TextField(blank=True, null=True)),
                ('tipomaterial', models.SmallIntegerField(default=0)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True)),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('autor', models.CharField(blank=True, max_length=50, null=True)),
                ('clasificacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'fichas',
            },
        ),
    ]
