# Generated by Django 6.0.3 on 2026-04-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='imports/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('terminado', 'Terminado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('progreso', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('procesados', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
