# Generated by Django 5.1.6 on 2025-03-02 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecarios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BibliotecarioBiblioteca',
        ),
    ]
