# Generated by Django 5.1.6 on 2025-03-08 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecarios', '0003_alter_bibliotecario_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliotecario',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Bibliotecario', 'verbose_name_plural': 'Bibliotecarios'},
        ),
        migrations.RemoveField(
            model_name='bibliotecario',
            name='user',
        ),
        migrations.AddField(
            model_name='bibliotecario',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bibliotecarios_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
