# Generated by Django 5.1.7 on 2025-04-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecarios', '0004_alter_bibliotecario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibliotecario',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bibliotecario',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('librarian', 'Bibliotecario'), ('visitor', 'Visitante')], default='librarian', max_length=50),
        ),
    ]
