# Generated by Django 5.1.7 on 2025-04-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecarios', '0005_bibliotecario_is_staff_alter_bibliotecario_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliotecario',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
