# Generated by Django 5.1.7 on 2025-04-15 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecarios', '0006_alter_bibliotecario_is_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibliotecario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='bibliotecario',
            name='role',
        ),
        migrations.AddField(
            model_name='bibliotecario',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bibliotecario', to=settings.AUTH_USER_MODEL),
        ),
    ]
