# Generated by Django 5.1.7 on 2025-04-08 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliotecas', '0003_biblioteca_latitud_biblioteca_longitud'),
        ('libros', '0009_alter_libro_numadqui'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_credencial', models.IntegerField(blank=True, null=True, verbose_name='No. Credencial')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reserva')),
                ('fecha_prestamo', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de préstamo')),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de devolución')),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('prestado', 'Prestado'), ('devuelto', 'Devuelto')], default='reservado', max_length=20, verbose_name='Estado')),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecas.biblioteca', verbose_name='Biblioteca')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro', verbose_name='Libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
            },
        ),
    ]
