# Generated by Django 5.2 on 2025-10-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestamo',
            options={'verbose_name': 'PrÃ©stamo', 'verbose_name_plural': 'PrÃ©stamos'},
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de devoluciÃ³n'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de prÃ©stamo'),
        ),
    ]
