# Generated by Django 5.1.6 on 2025-03-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la biblioteca')),
                ('nombre_corto', models.CharField(max_length=50, verbose_name='Nombre corto')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('director', models.CharField(max_length=255, verbose_name='Director')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('ubicacion', models.CharField(max_length=255)),
                ('reseña', models.TextField(verbose_name='Reseña')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('librarian', 'Bibliotecario'), ('visitor', 'Visitante')], max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='bibliotecas', verbose_name='Fotografía')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
        ),
    ]
