# Generated by Django 5.1.6 on 2025-03-09 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biblioteca',
            options={'verbose_name': 'Biblioteca', 'verbose_name_plural': 'Bibliotecas'},
        ),
    ]
