# Generated by Django 5.1.7 on 2025-03-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0002_alter_biblioteca_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
