# Generated by Django 5.2 on 2025-05-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0003_biblioteca_latitud_biblioteca_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblioteca',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='biblioteca',
            name='longitud',
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='num_coleccion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de coleccion'),
        ),
    ]
