# Generated by Django 5.2 on 2025-08-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0004_remove_biblioteca_latitud_remove_biblioteca_longitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='nombre_corto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre corto'),
        ),
    ]
