# Generated by Django 5.2 on 2025-08-19 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0005_alter_biblioteca_nombre_corto'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='closing_time',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='Hora de cierre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='opening_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Hora de apertura'),
            preserve_default=False,
        ),
    ]
