# Generated by Django 5.2 on 2025-07-24 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliotecas', '0004_remove_biblioteca_latitud_remove_biblioteca_longitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaCultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('lugar', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('enlace', models.URLField()),
                ('imagen', models.ImageField(upload_to='eventos/cultural/')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaBiblioAprende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('imagen', models.ImageField(upload_to='eventos/biblioaprende/')),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecas.biblioteca')),
            ],
        ),
    ]
