# Generated by Django 5.2 on 2025-08-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendabiblioaprende',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalizacion'),
        ),
        migrations.AddField(
            model_name='agendabiblioaprende',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Horario de finalizacion'),
        ),
    ]
