# Generated by Django 5.1.7 on 2025-03-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservasala',
            name='edad_rango',
        ),
        migrations.RemoveField(
            model_name='reservasala',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reservasala',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='reservasala',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='reservasala',
            name='telefono_responsable',
        ),
    ]
