# Generated by Django 5.2 on 2025-06-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_remove_reservasala_edad_rango_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasala',
            name='edad_rango',
            field=models.CharField(blank=True, choices=[('menores_12', 'Menores de 12 '), ('13_17', '13 a 17 '), ('18_29', '18 a 29 '), ('30_59', '30 a 59 '), ('mayores_60', 'Mayores de 60 ')], max_length=20, null=True, verbose_name='Rango de Edad'),
        ),
        migrations.AddField(
            model_name='reservasala',
            name='nombre_evento',
            field=models.CharField(default='Sin nombre', max_length=255, verbose_name='Nombre del evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservasala',
            name='nombre_institucion',
            field=models.CharField(default='Sin nombre', max_length=255, verbose_name='Nombre de la institucion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservasala',
            name='resena_proyecto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservasala',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='reservasala',
            name='tipo_evento',
            field=models.CharField(default='Sin nombre', max_length=255, verbose_name='Tipo de evento'),
            preserve_default=False,
        ),
    ]
