# Generated by Django 5.2 on 2025-06-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0003_reservasala_edad_rango_reservasala_nombre_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservasala',
            name='tipo_evento',
            field=models.CharField(choices=[('reunion', 'Reunion'), ('curso', 'Curso'), ('exhibicion', 'Exhibicion'), ('colaborativo', 'Trabajo colaborativo')], max_length=50, verbose_name='Tipo de evento'),
        ),
    ]
