# Generated by Django 5.1.6 on 2025-03-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='registro',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AddField(
            model_name='registro',
            name='username',
            field=models.CharField(default='default_username', max_length=255, unique=True, verbose_name='Nombre de usuario'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
    ]
