# Generated by Django 5.1.6 on 2025-03-02 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_registro_last_login_registro_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='registro',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
