# Generated by Django 5.1.6 on 2025-03-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_alter_registro_password_alter_registro_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registro',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
