# Generated by Django 5.1.6 on 2025-03-03 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_registro_is_staff_registro_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_vencimiento',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
