# Generated by Django 5.1.6 on 2025-03-03 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0001_initial'),
        ('registros', '0006_alter_registro_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='apellido_materno',
            field=models.CharField(max_length=255, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='apellido_paterno',
            field=models.CharField(max_length=255, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='biblioteca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecas.biblioteca'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='codigo_postal',
            field=models.CharField(max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='domicilio',
            field=models.CharField(max_length=255, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='escuela_trabajo',
            field=models.CharField(max_length=255, verbose_name='Escuela o trabajo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_vencimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nombres',
            field=models.CharField(max_length=255, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ocupacion',
            field=models.CharField(max_length=255, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visitante')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registro',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='telefono_escuela_trabajo',
            field=models.CharField(max_length=20, verbose_name='Teléfono de la escuela o trabajo'),
        ),
    ]
