# Generated by Django 5.1.6 on 2025-03-03 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0001_initial'),
        ('registros', '0008_alter_registro_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='biblioteca',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='bibliotecas.biblioteca'),
        ),
    ]
