# Generated by Django 5.1.6 on 2025-03-06 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bibliotecas', '0001_initial'),
        ('registros', '0009_alter_registro_biblioteca'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='registro',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='apellido_materno',
            field=models.CharField(max_length=255, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='apellido_paterno',
            field=models.CharField(max_length=255, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='biblioteca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecas.biblioteca'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='codigo_postal',
            field=models.CharField(max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='domicilio',
            field=models.CharField(max_length=255, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='escuela_trabajo',
            field=models.CharField(max_length=255, verbose_name='Escuela o trabajo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha_vencimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nombres',
            field=models.CharField(max_length=255, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ocupacion',
            field=models.CharField(max_length=255, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visitante')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registro',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='telefono_escuela_trabajo',
            field=models.CharField(max_length=20, verbose_name='Teléfono de la escuela o trabajo'),
        ),
    ]
