# Generated by Django 5.1.6 on 2025-03-09 23:17

import registros.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0011_migracion_personalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_vencimiento',
            field=models.DateField(default=registros.models.get_fecha_vencimiento_default),
        ),
    ]
