# Generated by Django 5.1.6 on 2025-03-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0012_alter_registro_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
