# Generated by Django 5.1.7 on 2025-03-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0013_registro_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
