# Generated by Django 5.1.7 on 2025-03-13 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0002_alter_biblioteca_options'),
        ('registros', '0014_alter_registro_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='biblioteca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliotecas.biblioteca'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='codigo_postal',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='domicilio',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='escuela_trabajo',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Escuela o trabajo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ocupacion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visitante')], default='visitor', max_length=50),
        ),
        migrations.AlterField(
            model_name='registro',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='telefono_escuela_trabajo',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono de la escuela o trabajo'),
        ),
    ]
