# Generated by Django 5.1.7 on 2025-04-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bibliotecas', '0003_biblioteca_latitud_biblioteca_longitud'),
        ('registros', '0015_alter_registro_biblioteca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='no_credencial',
            field=models.IntegerField(blank=True, null=True, verbose_name='No. Credencial'),
        ),
        migrations.AddConstraint(
            model_name='registro',
            constraint=models.UniqueConstraint(fields=('biblioteca', 'no_credencial'), name='unique_no_credencial_per_biblioteca'),
        ),
    ]
