# Generated by Django 5.1.7 on 2025-04-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0016_registro_no_credencial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visitante'), ('librarian', 'Bibliotecario')], default='visitor', max_length=50),
        ),
    ]
