# Generated by Django 5.2 on 2025-09-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('bibliotecas', '0006_biblioteca_closing_time_biblioteca_opening_time'),
        ('registros', '0017_alter_registro_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='escolaridad',
            field=models.CharField(blank=True, choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('preparatoria', 'Preparatoria'), ('tecnico', 'Técnico'), ('licenciatura', 'Licenciatura'), ('posgrado', 'Posgrado'), ('otra', 'Otra')], max_length=30, null=True, verbose_name='Escolaridad'),
        ),
        migrations.AddField(
            model_name='registro',
            name='numero_empleado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de empleado'),
        ),
        migrations.AddConstraint(
            model_name='registro',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'librarian')), fields=('numero_empleado',), name='unique_numero_empleado_librarian'),
        ),
    ]
