# Generated by Django 5.2 on 2025-10-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0018_registro_curp_registro_escolaridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='codigo_postal',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='CÃ³digo Postal'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrÃ³nico'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='escolaridad',
            field=models.CharField(blank=True, choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('preparatoria', 'Preparatoria'), ('tecnico', 'TÃ©cnico'), ('licenciatura', 'Licenciatura'), ('posgrado', 'Posgrado'), ('otra', 'Otra')], max_length=30, null=True, verbose_name='Escolaridad'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='numero_empleado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='NÃºmero de empleado'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ocupacion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='OcupaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='TelÃ©fono'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='telefono_escuela_trabajo',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='TelÃ©fono de la escuela o trabajo'),
        ),
    ]
