# Generated by Django 5.2 on 2026-01-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0019_alter_registro_codigo_postal_alter_registro_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='codigo_postal',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='escolaridad',
            field=models.CharField(blank=True, choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('preparatoria', 'Preparatoria'), ('tecnico', 'Técnico'), ('licenciatura', 'Licenciatura'), ('posgrado', 'Posgrado'), ('otra', 'Otra')], max_length=30, null=True, verbose_name='Escolaridad'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='numero_empleado',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de empleado'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ocupacion',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='telefono_escuela_trabajo',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono de la escuela o trabajo'),
        ),
    ]
