# Generated by Django 5.2 on 2025-05-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='adults_over_60_students',
            field=models.PositiveIntegerField(default=0, verbose_name='Mayores de 60 - Estudiantes'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='kids_0_to_12_secondary',
            field=models.PositiveIntegerField(default=0, verbose_name='- Secundaria'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='publications',
            field=models.PositiveIntegerField(default=0, verbose_name='Publicaciones periodicas'),
        ),
    ]
