# Generated by Django 5.2 on 2025-06-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0002_libraryvisitorstats_adults_over_60_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='adults_over_60_unemployed',
            field=models.PositiveIntegerField(default=0, verbose_name='mayores de 60  - Desempleados'),
        ),
    ]
