# Generated by Django 5.2 on 2025-10-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0003_alter_libraryvisitorstats_adults_over_60_unemployed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='adolescents_13_to_17_employed_or_worker',
            field=models.PositiveIntegerField(default=0, verbose_name=' 13 y 17 años - Empleado / Trabajador'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='adolescents_13_to_17_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Adolescentes entre 13 y 17 años - Mujeres'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='adolescents_13_to_17_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Adolescentes entre 13 y 17 años - Hombres'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='adolescents_13_to_17_unemployed',
            field=models.PositiveIntegerField(default=0, verbose_name=' 13 y 17 años - Desocupados'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='adults_30_to_59_employed_or_worker',
            field=models.PositiveIntegerField(default=0, verbose_name='30 y 59 años- Empleado / Trabajador'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='adults_30_to_59_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Adultos entre 30 y 59 años - Mujeres'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='adults_30_to_59_household',
            field=models.PositiveIntegerField(default=0, verbose_name='30 y 59 años - Hogar'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='adults_30_to_59_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Adultos entre 30 y 59 años - Hombres'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='adults_30_to_59_students',
            field=models.PositiveIntegerField(default=0, verbose_name='30 y 59 años- Estudiantes'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='adults_30_to_59_unemployed',
            field=models.PositiveIntegerField(default=0, verbose_name='30 y 59 años - Desocupados'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='adults_over_60_employed_or_worker',
            field=models.PositiveIntegerField(default=0, verbose_name='mayores de 60 años - Empleado / Trabajador'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='adults_over_60_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Adultos mayores de 60 años - Mujeres'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='adults_over_60_household',
            field=models.PositiveIntegerField(default=0, verbose_name='mayores de 60 años - Hogar'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='adults_over_60_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Adultos mayores de 60 años - Hombres'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='adults_over_60_students',
            field=models.PositiveIntegerField(default=0, verbose_name='Mayores de 60 años- Estudiantes'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='adults_over_60_unemployed',
            field=models.PositiveIntegerField(default=0, verbose_name='mayores de 60 años - Desocupados'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='kids_0_to_12_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Niños entre 0 y 12 años - Mujeres'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='kids_0_to_12_household',
            field=models.PositiveIntegerField(default=0, verbose_name='0 y 12 años - Hogar'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='kids_0_to_12_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Niños entre 0 y 12 años - Hombres'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='kids_0_to_12_preschool',
            field=models.PositiveIntegerField(default=0, verbose_name='Niños entre 0 y 12 años - Preescolar'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='kids_0_to_12_primary',
            field=models.PositiveIntegerField(default=0, verbose_name='Niños entre 0 y 12 años - Primaria'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='kids_0_to_12_students',
            field=models.PositiveIntegerField(default=0, verbose_name=' 0 y 12 años - Estudiantes'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='physical_loan',
            field=models.PositiveIntegerField(default=0, verbose_name='Préstamo a domicilio'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_adolescents_13_to_17_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Actividades de Fomento a la Lectura - Adolescentes entre 13 y 17 años (Mujeres)'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_adolescents_13_to_17_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Actividades de Fomento a la Lectura - Adolescentes entre 13 y 17 años (Hombres)'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_adults_30_to_59_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Actividades de Fomento a la Lectura - Adultos entre 30 y 59 años (Mujeres)'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_adults_30_to_59_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Actividades de Fomento a la Lectura - Adultos entre 30 y 59 años (Hombres)'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_adults_over_60_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Actividades de Fomento a la Lectura - Adultos mayores de 60 años (Mujeres)'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_adults_over_60_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Actividades de fomento a la Lectura - Adultos mayores de 60 años (Hombres)'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_children_0_to_12_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Actividades de Fomento a la Lectura - Niños entre 0 y 12 años (Mujeres)'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_children_0_to_12_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Actividades de Fomento a la Lectura - Niños entre 0 y 12 años (Hombres)'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_young_adults_18_to_29_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Actividades de Fomento a la Lectura - Adultos jóvenes entre 18 y 29 años (Mujeres)'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_young_adults_18_to_29_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Actividades de Fomento a la Lectura - Adultos jóvenes entre 18 y 29 años (Hombres)'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='young_adults_18_to_29_employed_or_worker',
            field=models.PositiveIntegerField(default=0, verbose_name=' 18 y 29 años - Empleado / Trabajador'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='young_adults_18_to_29_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Adultos jóvenes entre 18 y 29 años - Mujeres'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='young_adults_18_to_29_household',
            field=models.PositiveIntegerField(default=0, verbose_name=' 18 y 29 años - Hogar'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='young_adults_18_to_29_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Adultos jóvenes entre 18 y 29 años - Hombres'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='young_adults_18_to_29_students',
            field=models.PositiveIntegerField(default=0, verbose_name=' 18 y 29 años - Estudiantes'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='young_adults_18_to_29_unemployed',
            field=models.PositiveIntegerField(default=0, verbose_name=' 18 y 29 años - Desocupados'),
        ),
    ]
