# Generated by Django 5.2 on 2025-10-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0004_alter_libraryvisitorstats_adolescents_13_to_17_employed_or_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_adolescents_13_to_17_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Asistentes  - Adolescentes entre 13 y 17 años (Mujeres)'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_adolescents_13_to_17_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Asistentes - Adolescentes entre 13 y 17 años (Hombres)'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_adults_30_to_59_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Asistentes adultos  - Adultos entre 30 y 59 años (Mujeres)'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_adults_30_to_59_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Asistentes adultos  - Adultos entre 30 y 59 años (Hombres)'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_adults_over_60_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Asistentes adultos mayores de 60 hombres - Adultos mayores de 60 años (Mujeres)'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_adults_over_60_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Asistentes adultos mayores de 60 hombres - Adultos mayores de 60 años (Hombres)'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_children_0_to_12_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Asistentes - Niños entre 0 y 12 años (Mujeres)'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_children_0_to_12_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Asistentes  - Niños entre 0 y 12 años (Hombres)'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_young_adults_18_to_29_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Asistentes adultos  - Adultos jóvenes entre 18 y 29 años (Mujeres)'),
        ),
        migrations.AlterField(
            model_name='libraryvisitorstats',
            name='reading_promotion_young_adults_18_to_29_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Asistentes adultos  - Adultos jóvenes entre 18 y 29 años (Hombres)'),
        ),
    ]
