# Generated by Django 5.2 on 2026-02-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0005_alter_libraryvisitorstats_reading_promotion_adolescents_13_to_17_females_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEstadisticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('libros_general', models.PositiveIntegerField(default=0, verbose_name='General')),
                ('libros_consulta', models.PositiveIntegerField(default=0, verbose_name='Consulta')),
                ('libros_infantil', models.PositiveIntegerField(default=0, verbose_name='Infantil')),
                ('sep_titulos_consultados', models.TextField(blank=True, default='', verbose_name='Títulos más consultados en préstamo de colección')),
                ('sep_total_libros_prestados', models.PositiveIntegerField(default=0, verbose_name='Total de libros prestados')),
                ('sep_adults_over_60_males', models.PositiveIntegerField(default=0, verbose_name='SEP - Adultos mayores de 60 años (Hombres)')),
                ('sep_adults_over_60_females', models.PositiveIntegerField(default=0, verbose_name='SEP - Adultos mayores de 60 años (Mujeres)')),
                ('sep_adults_30_to_59_males', models.PositiveIntegerField(default=0, verbose_name='SEP - Adultos entre 30 y 59 años (Hombres)')),
                ('sep_adults_30_to_59_females', models.PositiveIntegerField(default=0, verbose_name='SEP - Adultos entre 30 y 59 años (Mujeres)')),
                ('sep_young_adults_18_to_29_males', models.PositiveIntegerField(default=0, verbose_name='SEP - Adultos jóvenes entre 18 y 29 años (Hombres)')),
                ('sep_young_adults_18_to_29_females', models.PositiveIntegerField(default=0, verbose_name='SEP - Adultos jóvenes entre 18 y 29 años (Mujeres)')),
                ('sep_adolescents_13_to_17_males', models.PositiveIntegerField(default=0, verbose_name='SEP - Adolescentes entre 13 y 17 años (Hombres)')),
                ('sep_adolescents_13_to_17_females', models.PositiveIntegerField(default=0, verbose_name='SEP - Adolescentes entre 13 y 17 años (Mujeres)')),
                ('sep_children_0_to_12_males', models.PositiveIntegerField(default=0, verbose_name='SEP - Niños entre 0 y 12 años (Hombres)')),
                ('sep_children_0_to_12_females', models.PositiveIntegerField(default=0, verbose_name='SEP - Niños entre 0 y 12 años (Mujeres)')),
                ('sep_mochila_viajera', models.BooleanField(default=False, verbose_name='La biblioteca ha realizado la actividad Mochila Viajera')),
                ('infra_ampliacion', models.BooleanField(default=False, verbose_name='Ampliación')),
                ('infra_remodelacion', models.BooleanField(default=False, verbose_name='Remodelación')),
                ('infra_reconstruccion', models.BooleanField(default=False, verbose_name='Reconstrucción')),
                ('infra_reubicacion', models.BooleanField(default=False, verbose_name='Reubicación')),
                ('infra_mantenimiento_basico', models.BooleanField(default=False, verbose_name='Mantenimiento Básico')),
                ('infra_equipamiento', models.BooleanField(default=False, verbose_name='Equipamiento')),
                ('infra_observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Datos Estadísticos',
                'verbose_name_plural': 'Datos Estadísticos',
            },
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='cultural_activity_type',
            field=models.CharField(blank=True, choices=[('', '-- Seleccione una actividad --'), ('conciertos', 'Conciertos'), ('teatro', 'Teatro'), ('danza', 'Danza'), ('proyecciones_cine', 'Proyecciones de Cine'), ('fotografia', 'Fotografía'), ('pintura', 'Pintura'), ('exposiciones', 'Exposiciones')], default='', max_length=50, verbose_name='Tipo de Actividad Cultural'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='cultural_adolescents_13_to_17_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Act. Cultural - Adolescentes entre 13 y 17 años (Mujeres)'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='cultural_adolescents_13_to_17_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Act. Cultural - Adolescentes entre 13 y 17 años (Hombres)'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='cultural_adults_30_to_59_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Act. Cultural - Adultos entre 30 y 59 años (Mujeres)'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='cultural_adults_30_to_59_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Act. Cultural - Adultos entre 30 y 59 años (Hombres)'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='cultural_adults_over_60_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Act. Cultural - Adultos mayores de 60 años (Mujeres)'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='cultural_adults_over_60_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Act. Cultural - Adultos mayores de 60 años (Hombres)'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='cultural_children_0_to_12_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Act. Cultural - Niños entre 0 y 12 años (Mujeres)'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='cultural_children_0_to_12_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Act. Cultural - Niños entre 0 y 12 años (Hombres)'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='cultural_young_adults_18_to_29_females',
            field=models.PositiveIntegerField(default=0, verbose_name='Act. Cultural - Adultos jóvenes entre 18 y 29 años (Mujeres)'),
        ),
        migrations.AddField(
            model_name='libraryvisitorstats',
            name='cultural_young_adults_18_to_29_males',
            field=models.PositiveIntegerField(default=0, verbose_name='Act. Cultural - Adultos jóvenes entre 18 y 29 años (Hombres)'),
        ),
    ]
