# Generated by Django 5.1.6 on 2025-03-01 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliotecas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=255, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=255, verbose_name='Apellido Materno')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres')),
                ('domicilio', models.CharField(max_length=255, verbose_name='Domicilio')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('ocupacion', models.CharField(max_length=255, verbose_name='Ocupación')),
                ('nombre_direccion_trabajo', models.CharField(max_length=255, verbose_name='Nombre de la dirección de trabajo')),
                ('telefono_trabajo', models.CharField(max_length=20, verbose_name='Teléfono de trabajo')),
                ('role', models.CharField(choices=[('visitor', 'Visitante')], max_length=50)),
                ('responsabilidad', models.BooleanField()),
                ('retraso', models.CharField(max_length=255)),
                ('suspension', models.CharField(max_length=255)),
                ('aviso_usuario', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecas.biblioteca')),
            ],
        ),
    ]
