# Generated by Django 5.1.6 on 2025-03-01 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliotecas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numadqui', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('autor', models.CharField(max_length=255, verbose_name='Autor')),
                ('isbn', models.CharField(max_length=20)),
                ('clasificacion', models.CharField(max_length=50, verbose_name='Clasificación')),
                ('subjects', models.JSONField(blank=True, null=True)),
                ('editor', models.CharField(blank=True, max_length=255, null=True)),
                ('publicacion_year', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('librarian', 'Bibliotecario'), ('visitor', 'Visitante')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecas.biblioteca')),
            ],
        ),
        migrations.CreateModel(
            name='CopiaLibro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=255)),
                ('numadqui', models.CharField(max_length=20)),
                ('fecha_adquisicion', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('localizacion_shelf', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biblioteca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.biblioteca')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
            ],
        ),
    ]
