# Generated by Django 5.1.6 on 2025-03-02 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0001_initial'),
        ('libros', '0004_alter_libro_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copialibro',
            name='biblioteca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotecas.biblioteca'),
        ),
        migrations.DeleteModel(
            name='Biblioteca',
        ),
    ]
