# Generated by Django 5.1.6 on 2025-03-06 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0001_initial'),
        ('libros', '0005_alter_copialibro_biblioteca_delete_biblioteca'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='busquedas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='comentarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='conversiones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='descargas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='devoluciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='favoritos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='impresiones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='lecturas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='prestamos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='reservas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='reseñas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='valoraciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='libro',
            name='vistas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libro',
            name='biblioteca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='bibliotecas.biblioteca'),
        ),
    ]
