# Generated by Django 5.1.6 on 2025-03-09 02:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_libro_busquedas_libro_clicks_libro_comentarios_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo', 'autor'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='publicacion_year',
            new_name='año_publicacion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='clasificacion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='user',
        ),
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.CharField(choices=[('fiction', 'Ficción'), ('nonfiction', 'No Ficción'), ('poetry', 'Poesía'), ('science', 'Ciencia'), ('history', 'Historia'), ('biography', 'Biografía'), ('children', 'Infantil'), ('other', 'Otro')], default='fiction', max_length=50),
        ),
        migrations.AddField(
            model_name='libro',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libros_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='libro',
            name='editorial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Editorial'),
        ),
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.CharField(choices=[('available', 'Disponible'), ('loaned', 'Prestado'), ('reserved', 'Reservado'), ('maintenance', 'En mantenimiento'), ('lost', 'Extraviado')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ubicación en biblioteca'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN'),
        ),
        migrations.DeleteModel(
            name='CopiaLibro',
        ),
    ]
