# Generated by Django 5.1.6 on 2025-03-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0007_alter_libro_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.CharField(choices=[('fiction', 'Ficción'), ('nonfiction', 'No Ficción'), ('poetry', 'Poesía'), ('science', 'Ciencia'), ('literature', 'Literario'), ('history', 'Historia'), ('biography', 'Biografía'), ('children', 'Infantil'), ('other', 'Otro')], default='fiction', max_length=50),
        ),
    ]
