# Generated by Django 5.1.7 on 2025-04-02 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
        ('libros', '0008_alter_libro_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='numadqui',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='libro', to='fichas.ficha'),
        ),
    ]
