# Generated by Django 5.1.7 on 2025-04-10 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0003_biblioteca_latitud_biblioteca_longitud'),
        ('fichas', '0001_initial'),
        ('libros', '0009_alter_libro_numadqui'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['titulo'], name='libros_libr_titulo_8b1204_idx'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['autor'], name='libros_libr_autor_285ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['isbn'], name='libros_libr_isbn_88473c_idx'),
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['estado'], name='libros_libr_estado_211437_idx'),
        ),
    ]
