# Generated by Django 5.1.7 on 2025-04-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0010_libro_libros_libr_titulo_8b1204_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='estado',
            field=models.CharField(choices=[('available', 'Disponible'), ('loaned', 'Prestado'), ('reserved', 'Reservado'), ('repair', 'En Reparacion'), ('lost', 'Extraviado')], default='available', max_length=20),
        ),
    ]
