# Generated by Django 5.1.7 on 2025-03-27 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliotecas', '0002_alter_biblioteca_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaGuiada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(max_length=255, verbose_name='Nombre de la institución')),
                ('nombre_director', models.CharField(max_length=255, verbose_name='Nombre del director')),
                ('fecha_visita', models.DateTimeField(verbose_name='Fecha de la Visita')),
                ('proposito', models.CharField(max_length=255, verbose_name='Propósito de la Visita')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono de la institución')),
                ('edad_rango', models.CharField(blank=True, choices=[('menores_12', 'Menores de 12 años'), ('13_17', '13 a 17 años'), ('18_29', '18 a 29 años'), ('30_59', '30 a 59 años'), ('mayores_60', 'Mayores de 60 años')], max_length=20, null=True, verbose_name='Rango de Edad')),
                ('total_asistencia', models.IntegerField(blank=True, null=True, verbose_name='Total de Asistencia')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico institucional')),
                ('apellido_paterno', models.CharField(max_length=255, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=255, verbose_name='Apellido Materno')),
                ('nombre_resp', models.CharField(max_length=255, verbose_name='Nombre del Responsable')),
                ('ocupacion', models.CharField(blank=True, default='', max_length=255, verbose_name='Ocupación')),
                ('telefono_resp', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono del Responsable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horario', models.CharField(blank=True, choices=[('08_10', '8:00 AM - 10:00 AM'), ('08_11', '8:00 AM - 12:00 AM'), ('09_12', '09:00 AM - 12:00 PM'), ('10_12', '10:00 AM - 12:00 PM'), ('10_13', '10:00 AM - 1:00 PM'), ('12_13', '12:00 PM - 4:00 PM'), ('13_14', '1:00 PM - 5:00 PM'), ('14_15', '2:00 PM - 6:00 PM'), ('15_16', '3:00 PM - 6:00 PM'), ('16_17', '4:00 PM - 7:00 PM'), ('17_18', '5:00 PM - 8:00 PM')], max_length=20, null=True, verbose_name='Horario de Llegada')),
                ('biblioteca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliotecas.biblioteca')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
            },
        ),
    ]
