# Generated by Django 5.2 on 2025-06-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaguiada',
            name='fecha_visita',
            field=models.DateField(verbose_name='Fecha de la Visita'),
        ),
    ]
