# Generated by Django 5.2 on 2025-07-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0002_alter_visitaguiada_fecha_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaguiada',
            name='horario',
            field=models.CharField(blank=True, choices=[('08_09', '8:00 AM - 09:00 AM'), ('09_10', '9:00 AM - 10:00 AM'), ('10_11', '10:00 AM - 11:00 AM'), ('11_12', '11:00 AM - 12:00 PM'), ('12_01', '12:00 AM - 1:00 PM'), ('02_03', '2:00 PM - 3:00 PM'), ('03_04', '3:00 PM - 4:00 PM'), ('04_05', '4:00 PM - 5:00 PM'), ('05_06', '5:00 PM - 6:00 PM'), ('06_07', '6:00 PM - 7:00 PM'), ('07_08', '7:00 PM - 8:00 PM')], max_length=20, null=True, verbose_name='Horario de Llegada'),
        ),
    ]
