# Generated by Django 5.2 on 2026-01-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita', '0003_alter_visitaguiada_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaguiada',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico institucional'),
        ),
    ]
