# Generated by Django 5.1.7 on 2025-03-25 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PreRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=255, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=255, verbose_name='Apellido Materno')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres')),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('domicilio', models.CharField(blank=True, default='', max_length=255, verbose_name='Domicilio')),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=10, verbose_name='Código Postal')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Nombre de usuario')),
                ('ocupacion', models.CharField(blank=True, default='', max_length=255, verbose_name='Ocupación')),
                ('escuela_trabajo', models.CharField(blank=True, default='', max_length=255, verbose_name='Escuela o trabajo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('biblioteca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preregistro.biblioteca')),
            ],
            options={
                'verbose_name': 'Preregistro',
                'verbose_name_plural': 'Preregistros',
            },
        ),
    ]
