# Generated by Django 5.1.7 on 2025-03-25 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotecas', '0002_alter_biblioteca_options'),
        ('preregistro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistro',
            name='biblioteca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliotecas.biblioteca'),
        ),
        migrations.DeleteModel(
            name='Biblioteca',
        ),
    ]
