# Generated by Django 5.1.7 on 2025-04-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0002_alter_preregistro_biblioteca_delete_biblioteca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistro',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
