# Generated by Django 5.2 on 2025-05-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0003_alter_preregistro_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preregistro',
            name='edad',
        ),
        migrations.AddField(
            model_name='preregistro',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='preregistro',
            name='entidad_federativa',
            field=models.CharField(choices=[('BC', 'Baja California'), ('BS', 'Baja California Sur'), ('CH', 'Chihuahua'), ('DF', 'Ciudad de México'), ('JC', 'Jalisco'), ('MC', 'México'), ('NL', 'Nuevo León'), ('OC', 'Oaxaca')], default='CH', max_length=2, verbose_name='Entidad Federativa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preregistro',
            name='fecha_nacimiento',
            field=models.DateField(default='1900-01-01', verbose_name='Fecha de Nacimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preregistro',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', max_length=1, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
