# Generated by Django 5.2 on 2025-06-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preregistro', '0004_remove_preregistro_edad_preregistro_curp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preregistro',
            name='entidad_federativa',
        ),
        migrations.AlterField(
            model_name='preregistro',
            name='curp',
            field=models.CharField(default='XXXXXXXXXX', max_length=18, unique=True),
            preserve_default=False,
        ),
    ]
